version: '3'
services:
  app:
    build: .
    container_name: notes-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DB_URL: mongodb://mongo:27017/notes_db 
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
